# Generated by Django 2.0.6 on 2018-06-18 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20151124_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='courses.Course'),
        ),
    ]
