# Generated by Django 2.0.6 on 2018-06-18 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_auto_20180618_1256'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('text', models.CharField(max_length=255)),
                ('correct', models.BooleanField(default=False)),
                ('qustion', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='courses.Question')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
