# Generated by Django 2.0.6 on 2018-06-18 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_answer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='qustion',
            new_name='question',
        ),
    ]
