# Generated by Django 2.0.6 on 2018-06-21 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_quiz_times_taken'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_live',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[('i', 'In Progress'), ('r', 'In Review'), ('p', 'Published')], default='i', max_length=1),
        ),
    ]
